name: Code Quality Checks

on: [push, pull_request]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black bandit

    - name: Check code formatting with black (dry-run)
      run: black . --check --exclude '/(env|external_libs)/'

    - name: Security analysis with Bandit
      run: bandit -r .
