name: Deploy Django App to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.9' 

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Deploy to AWS EC2
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        sudo apt-get update
        sudo apt-get install -y sshpass
        echo "${SSH_KEY}" > deploy_key
        chmod 600 deploy_key
        mkdir -p ~/.ssh
        touch ~/.ssh/known_hosts
        ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
        scp -i deploy_key -o StrictHostKeyChecking=no ./manage.py $USERNAME@$HOST:/path/to/your/django/app/your_project/settings/
        scp -i deploy_key -o StrictHostKeyChecking=no ./requirements.txt $USERNAME@$HOST:/path/to/your/django/app/
        ssh -i deploy_key -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
          cd /path/to/your/django/app 
          source venv/bin/activate
          pip install -r requirements.txt
          ./manage.py migrate
          ./manage.py collectstatic --noinput
          sudo systemctl restart gunicorn.service
        EOF
