name: Deploy Django App to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.9' 

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_KEY }}
    - name: Deploy to AWS EC2
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        sudo chown -R $ubuntu:$ubuntu /home/ubuntu/irentstuff
        RSYNC_RSH="ssh -o StrictHostKeyChecking=no" rsync -avz --exclude '.git/' --exclude 'venv/' --exclude 'db.sqlite3/' . $USERNAME@$HOST:/home/ubuntu/irentstuff
        
        ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << EOF
          cd /home/ubuntu/
          source /venv/bin/activate
          pip install -r requirements.txt
          chmod +x manage.py
          ./manage.py migrate

          sudo chown www-data:www-data irentstuff
          sudo chown www-data:www-data db.sqlite3
          sudo chown -R www-data:www-data irentstuff/media
    
          
          
          sudo systemctl restart apache2.service # add restart service
        EOF
