name: Unit tests with Django

on: [push, pull_request]

jobs:
  django_unit_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.9

    - name: Install requirements
      run: |
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        coverage run manage.py test
        coverage report
        COVERAGE_DATE=$(date +%Y%m%d)
        COVERAGE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's#/#_#g')
        mkdir -p coverage_reports
        coverage html -d coverage_reports/

    - name: Debug
      run: |
        echo "COVERAGE_DATE: $COVERAGE_DATE"
        echo "COVERAGE_BRANCH: $COVERAGE_BRANCH"

    - name: Archive coverage HTML report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report-${COVERAGE_DATE}-${COVERAGE_BRANCH}
        path: coverage_reports/

    - name: Output HTML report link
      run: |
        COVERAGE_DATE=$(date +%Y%m%d)
        COVERAGE_BRANCH=$(echo ${GITHUB_REF#refs/heads/} | sed 's#/#_#g')
        echo "::set-output name=COVERAGE_REPORT_LINK::file://${PWD}/coverage_reports/${COVERAGE_DATE}_${COVERAGE_BRANCH}/index.html"
        echo "HTML coverage report: \e]8;;${COVERAGE_REPORT_LINK}\e\\Click here\e]8;;\e\\"
