name: Unit tests with Pytest

on: [push, pull_request]

jobs:
  unt_tests_with_pytest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.10.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.10.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run Unit Tests
      run: |
        pytest