name: Lint

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Unit testing with pytest
      run: |
        pytest